/*
 * Quantizer library
 * Rich Holmes
 * 
 * Based on:
 * =======
 * TELEXo Eurorack Module
 * (c) 2016 Brendon Cassidy
 * MIT License
 * =======
 *
 * Mods include:
 * Get rid of frequency stuff, we don't need it. Can always calculate it
 * from Value anyway.
 *
 * Use avr/pgmspace to put scale data in program space, saving
 * dynamic memory.
 *
 */
 
#ifndef Quantizer_h
#define Quantizer_h

#include "Arduino.h"
#include <avr/pgmspace.h>

#define DACTOP 4095   // limit of DAC (2**12-1)
#define DAC1   4095   // DAC counts corresponding to defined voltage
#define V1     5.0    // voltage corresponding to DAC1
#define DACPEROCTAVE  (DAC1/V1)  // DAC counts per octave

struct QuantizeResponse {
  int Note; 
  int Value;
};

/*
 * Quantizes values 0-4095 to various tuning systems
 * some of this class is auto-generated by the associated python scripts
 */
class Quantizer
{
  public:

    Quantizer();
    Quantizer(int scale);
    QuantizeResponse Quantize(int in);
    void SetScale(int scale);
    float GetValueForNote(int note);

    // Bank and scale stuff
    Quantizer(int bank, int scale);
    void SetScale(int bank, int scale);

  protected:

    static const int PROGMEM bankandscale[6][12]; // index from bank-and-scale to scale

    // INSERT AUTOGENERATED SCALE HEADER DATA HERE
const static int scaleCount = 66;
static const int *hints[66];
static const float *scales[66];
static const int notecount[66];

static const float PROGMEM scale0[62];
static const int PROGMEM hints0[62];
static const float PROGMEM scale1[37];
static const int PROGMEM hints1[37];
static const float PROGMEM scale2[62];
static const int PROGMEM hints2[62];
static const float PROGMEM scale3[37];
static const int PROGMEM hints3[37];
static const float PROGMEM scale4[67];
static const int PROGMEM hints4[67];
static const float PROGMEM scale5[217];
static const int PROGMEM hints5[217];
static const float PROGMEM scale6[27];
static const int PROGMEM hints6[27];
static const float PROGMEM scale7[37];
static const int PROGMEM hints7[37];
static const float PROGMEM scale8[62];
static const int PROGMEM hints8[62];
static const float PROGMEM scale9[87];
static const int PROGMEM hints9[87];
static const float PROGMEM scale10[27];
static const int PROGMEM hints10[27];
static const float PROGMEM scale11[37];
static const int PROGMEM hints11[37];
static const float PROGMEM scale12[62];
static const int PROGMEM hints12[62];
static const float PROGMEM scale13[97];
static const int PROGMEM hints13[97];
static const float PROGMEM scale14[157];
static const int PROGMEM hints14[157];
static const float PROGMEM scale15[27];
static const int PROGMEM hints15[27];
static const float PROGMEM scale16[37];
static const int PROGMEM hints16[37];
static const float PROGMEM scale17[62];
static const int PROGMEM hints17[62];
static const float PROGMEM scale18[97];
static const int PROGMEM hints18[97];
static const float PROGMEM scale19[27];
static const int PROGMEM hints19[27];
static const float PROGMEM scale20[37];
static const int PROGMEM hints20[37];
static const float PROGMEM scale21[62];
static const int PROGMEM hints21[62];
static const float PROGMEM scale22[62];
static const int PROGMEM hints22[62];
static const float PROGMEM scale23[62];
static const int PROGMEM hints23[62];
static const float PROGMEM scale24[62];
static const int PROGMEM hints24[62];
static const float PROGMEM scale25[62];
static const int PROGMEM hints25[62];
static const float PROGMEM scale26[62];
static const int PROGMEM hints26[62];
static const float PROGMEM scale27[62];
static const int PROGMEM hints27[62];
static const float PROGMEM scale28[62];
static const int PROGMEM hints28[62];
static const float PROGMEM scale29[62];
static const int PROGMEM hints29[62];
static const float PROGMEM scale30[62];
static const int PROGMEM hints30[62];
static const float PROGMEM scale31[62];
static const int PROGMEM hints31[62];
static const float PROGMEM scale32[62];
static const int PROGMEM hints32[62];
static const float PROGMEM scale33[62];
static const int PROGMEM hints33[62];
static const float PROGMEM scale34[7];
static const int PROGMEM hints34[7];
static const float PROGMEM scale35[12];
static const int PROGMEM hints35[12];
static const float PROGMEM scale36[17];
static const int PROGMEM hints36[17];
static const float PROGMEM scale37[22];
static const int PROGMEM hints37[22];
static const float PROGMEM scale38[27];
static const int PROGMEM hints38[27];
static const float PROGMEM scale39[32];
static const int PROGMEM hints39[32];
static const float PROGMEM scale40[37];
static const int PROGMEM hints40[37];
static const float PROGMEM scale41[42];
static const int PROGMEM hints41[42];
static const float PROGMEM scale42[47];
static const int PROGMEM hints42[47];
static const float PROGMEM scale43[52];
static const int PROGMEM hints43[52];
static const float PROGMEM scale44[57];
static const int PROGMEM hints44[57];
static const float PROGMEM scale45[67];
static const int PROGMEM hints45[67];
static const float PROGMEM scale46[72];
static const int PROGMEM hints46[72];
static const float PROGMEM scale47[77];
static const int PROGMEM hints47[77];
static const float PROGMEM scale48[82];
static const int PROGMEM hints48[82];
static const float PROGMEM scale49[87];
static const int PROGMEM hints49[87];
static const float PROGMEM scale50[92];
static const int PROGMEM hints50[92];
static const float PROGMEM scale51[97];
static const int PROGMEM hints51[97];
static const float PROGMEM scale52[102];
static const int PROGMEM hints52[102];
static const float PROGMEM scale53[107];
static const int PROGMEM hints53[107];
static const float PROGMEM scale54[112];
static const int PROGMEM hints54[112];
static const float PROGMEM scale55[117];
static const int PROGMEM hints55[117];
static const float PROGMEM scale56[122];
static const int PROGMEM hints56[122];
static const float PROGMEM scale57[37];
static const int PROGMEM hints57[37];
static const float PROGMEM scale58[37];
static const int PROGMEM hints58[37];
static const float PROGMEM scale59[37];
static const int PROGMEM hints59[37];
static const float PROGMEM scale60[27];
static const int PROGMEM hints60[27];
static const float PROGMEM scale61[27];
static const int PROGMEM hints61[27];
static const float PROGMEM scale62[32];
static const int PROGMEM hints62[32];
static const float PROGMEM scale63[17];
static const int PROGMEM hints63[17];
static const float PROGMEM scale64[17];
static const int PROGMEM hints64[17];
static const float PROGMEM scale65[22];
static const int PROGMEM hints65[22];

    // END AUTOGENERATED SCALE HEADER DATA
      
  private:
    
    int _scale;
    int _octave;
    int _index;
    int _nudge;
    int _above;
    int _below;
    int _current;
    QuantizeResponse _last;

    int _temp;

};

#endif

