/*
 * Quantizer library
 * Rich Holmes
 * 
 * Based on:
 * =======
 * TELEXo Eurorack Module
 * (c) 2016 Brendon Cassidy
 * MIT License
 * =======
 *
 * Mods include:
 * Get rid of frequency stuff, we don't need it. Can always calculate it
 * from Value anyway.
 *
 * Use avr/pgmspace to put scale data in program space, saving
 * dynamic memory.
 *
 */
 
#ifndef Quantizer_h
#define Quantizer_h

#include "Arduino.h"
#include <avr/pgmspace.h>

#define DACTOP 4095   // limit of DAC (2**12-1)
#define DAC1   4095   // DAC counts corresponding to defined voltage
#define V1     5.0    // voltage corresponding to DAC1
#define DACPEROCTAVE  (DAC1/V1)  // DAC counts per octave

struct QuantizeResponse {
  int Note; 
  int Value;
};

/*
 * Quantizes values 0-4095 to various tuning systems
 * some of this class is auto-generated by the associated python scripts
 */
class Quantizer
{
  public:

    Quantizer();
    Quantizer(int scale);
    QuantizeResponse Quantize(int in);
    void SetScale(int scale);
    float GetValueForNote(int note);

    // Bank and scale stuff
    Quantizer(int bank, int scale);
    void SetScale(int bank, int scale);

  protected:

    static const int PROGMEM bankandscale[12][12]; // index from bank-and-scale to scale

    // INSERT AUTOGENERATED SCALE HEADER DATA HERE
const static int scaleCount = 13;
static const int *hints[13];
static const float *scales[13];
static const int notecount[13];

static const float PROGMEM scale0[62];
static const int PROGMEM hints0[62];
static const float PROGMEM scale1[37];
static const int PROGMEM hints1[37];
static const float PROGMEM scale2[37];
static const int PROGMEM hints2[37];
static const float PROGMEM scale3[37];
static const int PROGMEM hints3[37];
static const float PROGMEM scale4[37];
static const int PROGMEM hints4[37];
static const float PROGMEM scale5[37];
static const int PROGMEM hints5[37];
static const float PROGMEM scale6[37];
static const int PROGMEM hints6[37];
static const float PROGMEM scale7[37];
static const int PROGMEM hints7[37];
static const float PROGMEM scale8[27];
static const int PROGMEM hints8[27];
static const float PROGMEM scale9[27];
static const int PROGMEM hints9[27];
static const float PROGMEM scale10[27];
static const int PROGMEM hints10[27];
static const float PROGMEM scale11[27];
static const int PROGMEM hints11[27];
static const float PROGMEM scale12[27];
static const int PROGMEM hints12[27];

    // END AUTOGENERATED SCALE HEADER DATA
      
  private:
    
    int _scale;
    int _octave;
    int _index;
    int _nudge;
    int _above;
    int _below;
    int _current;
    QuantizeResponse _last;

    int _temp;

};

#endif

